name: CI logaxi lib

on:
  pull_request:
    branches:
      - "main"

  push:
    branches-ignore:
      - "main"

jobs:
  build-and-test:
    name: Build and Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Config Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
      - name: Dependencies Install
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Run Build
        run: npm run build
